# Generated by Django 3.1.14 on 2023-01-22 12:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0006_auto_20230122_1511'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShoppingCard',
            new_name='ShoppingCart',
        ),
    ]
