# Generated by Django 3.1.4 on 2023-01-30 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='is_favorite',
            new_name='is_favorited',
        ),
    ]
