# Generated by Django 3.1.14 on 2023-01-22 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20230122_1453'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoriterecipe',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='favoriterecipe',
            name='unique_favorite',
        ),
    ]
